INSERT INTO departament (id, name) VALUES (15, 'Lima');
INSERT INTO district (departament_id, name) VALUES (15, 'Lima');
INSERT INTO district (departament_id, name) VALUES (15, 'Ancón');
INSERT INTO district (departament_id, name) VALUES (15, 'Ate');
INSERT INTO district (departament_id, name) VALUES (15, 'Barranco');
INSERT INTO district (departament_id, name) VALUES (15, 'Breña');
INSERT INTO district (departament_id, name) VALUES (15, 'Carabayllo');
INSERT INTO district (departament_id, name) VALUES (15, 'Chaclacayo');
INSERT INTO district (departament_id, name) VALUES (15, 'Chorrillos');
INSERT INTO district (departament_id, name) VALUES (15, 'Cieneguilla');
INSERT INTO district (departament_id, name) VALUES (15, 'Comas');
INSERT INTO district (departament_id, name) VALUES (15, 'El Agustino');
INSERT INTO district (departament_id, name) VALUES (15, 'Independencia');
INSERT INTO district (departament_id, name) VALUES (15, 'Jesús María');
INSERT INTO district (departament_id, name) VALUES (15, 'La Molina');
INSERT INTO district (departament_id, name) VALUES (15, 'La Victoria');
INSERT INTO district (departament_id, name) VALUES (15, 'Lince');
INSERT INTO district (departament_id, name) VALUES (15, 'Los Olivos');
INSERT INTO district (departament_id, name) VALUES (15, 'Lurigancho');
INSERT INTO district (departament_id, name) VALUES (15, 'Lurin');
INSERT INTO district (departament_id, name) VALUES (15, 'Magdalena del Mar');
INSERT INTO district (departament_id, name) VALUES (15, 'Pueblo Libre');
INSERT INTO district (departament_id, name) VALUES (15, 'Miraflores');
INSERT INTO district (departament_id, name) VALUES (15, 'Pachacamac');
INSERT INTO district (departament_id, name) VALUES (15, 'Pucusana');
INSERT INTO district (departament_id, name) VALUES (15, 'Puente Piedra');
INSERT INTO district (departament_id, name) VALUES (15, 'Punta Hermosa');
INSERT INTO district (departament_id, name) VALUES (15, 'Punta Negra');
INSERT INTO district (departament_id, name) VALUES (15, 'Rímac');
INSERT INTO district (departament_id, name) VALUES (15, 'San Bartolo');
INSERT INTO district (departament_id, name) VALUES (15, 'San Borja');
INSERT INTO district (departament_id, name) VALUES (15, 'San Isidro');
INSERT INTO district (departament_id, name) VALUES (15, 'San Juan de Lurigancho');
INSERT INTO district (departament_id, name) VALUES (15, 'San Juan de Miraflores');
INSERT INTO district (departament_id, name) VALUES (15, 'San Luis');
INSERT INTO district (departament_id, name) VALUES (15, 'San Martín de Porres');
INSERT INTO district (departament_id, name) VALUES (15, 'San Miguel');
INSERT INTO district (departament_id, name) VALUES (15, 'Santa Anita');
INSERT INTO district (departament_id, name) VALUES (15, 'Santa María del Mar');
INSERT INTO district (departament_id, name) VALUES (15, 'Santa Rosa');
INSERT INTO district (departament_id, name) VALUES (15, 'Santiago de Surco');
INSERT INTO district (departament_id, name) VALUES (15, 'Surquillo');
INSERT INTO district (departament_id, name) VALUES (15, 'Villa El Salvador');
INSERT INTO district (departament_id, name) VALUES (15, 'Villa María del Triunfo');
INSERT INTO typestore (id, fullname) VALUES (1, 'Otros');
INSERT INTO typestore (id, fullname) VALUES (2, 'Librería');
INSERT INTO typestore (id, fullname) VALUES (3, 'Locutorios');
INSERT INTO typestore (id, fullname) VALUES (4, 'Farmacia');
INSERT INTO typestore (id, fullname) VALUES (5, 'Casa de Cambio');
INSERT INTO typestore (id, fullname) VALUES (6, 'Bodega');
INSERT INTO typestore (id, fullname) VALUES (7, 'Mini Market');
INSERT INTO typestore (id, fullname) VALUES (8, 'Puesto de Mercado');
INSERT INTO typestore (id, fullname) VALUES (9, 'Centros de Cobranza');
INSERT INTO typestore (id, fullname) VALUES (10,'Tiendas Comerciales');
INSERT INTO typestore (id, fullname) VALUES (11,'Agencia de Viajes');
INSERT INTO typestore (id, fullname) VALUES (12,'Mayoristas');
INSERT INTO typestore (id, fullname) VALUES (13,'Mercado');
INSERT INTO typestore (id, fullname) VALUES (14,'AASS');
INSERT INTO typestore (id, fullname) VALUES (15,'Minoristas');

